export const fontSize = {
  "button-l": "var(--typography-button-l-font-size)",
  "button-m": "var(--typography-button-m-font-size)",
  "caption-m": "var(--typography-caption-m-font-size)",
  "caption-s": "var(--typography-caption-s-all-caps-font-size)",
  "code-paragraph": "var(--typography-code-paragraph-font-size)",
  "code-tag": "var(--typography-code-tag-font-size)",
  h1: "var(--typography-heading-h1-font-size)",
  h2: "var(--typography-heading-h2-font-size)",
  h3: "var(--typography-heading-h3-font-size)",
  h4: "var(--typography-heading-h4-font-size)",
  h5: "var(--typography-heading-h5-font-size)",
  "label-m-bold": "var(--typography-label-m-bold-font-size)",
  "label-m-regular": "var(--typography-label-m-regular-font-size)",
  "label-s-bold": "var(--typography-label-s-bold-font-size)",
  "label-s-regular": "var(--typography-label-s-regular-font-size)",
  navigation: "var(--typography-navigation-font-size)",
  "overline-m": "var(--typography-overline-m-font-size)",
  "paragraph-l": "var(--typography-paragraph-l-font-size)",
  "paragraph-m": "var(--typography-paragraph-m-font-size)",
  "tag-l": "var(--typography-tag-l-font-size)",
  "tag-m": "var(--typography-tag-m-font-size)",
  "tag-s": "var(--typography-tag-s-font-size)",
  title: "var(--typography-title-font-size)",
};
