export const letterSpacing = {
  "button-l": "var(--typography-button-l-letter-spacing)",
  "button-m": "var(--typography-button-m-letter-spacing)",
  "caption-m": "var(--typography-caption-m-letter-spacing)",
  "caption-s": "var(--typography-caption-s-all-caps-letter-spacing)",
  "code-paragraph": "var(--typography-code-paragraph-letter-spacing)",
  "code-tag": "var(--typography-code-tag-letter-spacing)",
  h1: "var(--typography-heading-h1-letter-spacing)",
  h2: "var(--typography-heading-h2-letter-spacing)",
  h3: "var(--typography-heading-h3-letter-spacing)",
  h4: "var(--typography-heading-h4-letter-spacing)",
  h5: "var(--typography-heading-h5-letter-spacing)",
  "label-m-bold": "var(--typography-label-m-bold-letter-spacing)",
  "label-m-regular": "var(--typography-label-m-regular-letter-spacing)",
  "label-s-bold": "var(--typography-label-s-bold-letter-spacing)",
  "label-s-regular": "var(--typography-label-s-regular-letter-spacing)",
  navigation: "var(--typography-navigation-letter-spacing)",
  "overline-m": "var(--typography-overline-m-letter-spacing)",
  "paragraph-l": "var(--typography-paragraph-l-letter-spacing)",
  "paragraph-m": "var(--typography-paragraph-m-letter-spacing)",
  "tag-l": "var(--typography-tag-l-letter-spacing)",
  "tag-m": "var(--typography-tag-m-letter-spacing)",
  "tag-s": "var(--typography-tag-s-letter-spacing)",
  title: "var(--typography-title-letter-spacing)",
};
