export const lineHeight = {
  "button-l": "var(--typography-button-l-line-height)",
  "button-m": "var(--typography-button-m-line-height)",
  "caption-m": "var(--typography-caption-m-line-height)",
  "caption-s": "var(--typography-caption-s-all-caps-line-height)",
  "code-paragraph": "var(--typography-code-paragraph-line-height)",
  "code-tag": "var(--typography-code-tag-line-height)",
  h1: "var(--typography-heading-h1-line-height)",
  h2: "var(--typography-heading-h2-line-height)",
  h3: "var(--typography-heading-h3-line-height)",
  h4: "var(--typography-heading-h4-line-height)",
  h5: "var(--typography-heading-h5-line-height)",
  "label-m-bold": "var(--typography-label-m-bold-line-height)",
  "label-m-regular": "var(--typography-label-m-regular-line-height)",
  "label-s-bold": "var(--typography-label-s-bold-line-height)",
  "label-s-regular": "var(--typography-label-s-regular-line-height)",
  navigation: "var(--typography-navigation-line-height)",
  "overline-m": "var(--typography-overline-m-line-height)",
  "paragraph-l": "var(--typography-paragraph-l-line-height)",
  "paragraph-m": "var(--typography-paragraph-m-line-height)",
  "tag-l": "var(--typography-tag-l-line-height)",
  "tag-m": "var(--typography-tag-m-line-height)",
  "tag-s": "var(--typography-tag-s-line-height)",
  title: "var(--typography-title-line-height)",
};
